
---

## `.github/workflows/ci.yml`

```yaml
name: ci
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        preset: [default, release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install cmake ninja libomp || true

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --parallel

      - name: Test
        if: matrix.preset == 'default'
        run: ctest --preset ${{ matrix.preset }} --output-on-failure

