name: Build and release binaries

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ---- Linux (portable glibc 2.17) ----
  build-linux:
    name: Build (linux-x86_64 glibc2.17)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build inside manylinux2014 container
        run: |
          docker run --rm -v "$PWD":/io -w /io quay.io/pypa/manylinux2014_x86_64 bash -lc '
          set -euxo pipefail
          source /opt/rh/devtoolset-10/enable
          /opt/python/cp311-cp311/bin/python -m pip install --upgrade pip
          /opt/python/cp311-cp311/bin/pip install cmake ninja
          export PATH="/opt/python/cp311-cp311/bin:$PATH"
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLDSC_PORTABLE_LINUX=ON
          cmake --build build --parallel
          mkdir -p dist bundle
          cp build/ldsc bundle/ldsc
          strip bundle/ldsc || true
          for f in LICENSE AUTHORS NOTICE CREDITS; do [ -f "$f" ] && cp "$f" bundle/ || true; done
          tar czf dist/ldsc_linux-x86_64_glibc2.17.tar.gz -C bundle .
        '

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldsc-linux-x86_64-glibc2.17
          path: dist/*

  # ---- macOS + Windows ----
  build:
    name: Build (${{ matrix.triplet }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            triplet: macos-x86_64
            configure: macos-release
          - os: macos-14
            triplet: macos-arm64
            configure: macos-release
          - os: windows-latest
            triplet: windows-x86_64
            configure: windows-release-staticcrt
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          cmake --version
          ninja --version || true

      - name: Install OpenMP runtime (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew list --versions libomp >/dev/null || brew install libomp

      - name: Toolchain (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja -y || powershell -Command "Write-Host 'ninja likely present'"
          ninja --version

      - name: Configure
        run: cmake -S . -B build -G Ninja --preset ${{ matrix.configure }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist,bundle | Out-Null
          $exe = "build/ldsc.exe"
          if (Test-Path "build/Release/ldsc.exe") { $exe = "build/Release/ldsc.exe" }
          Copy-Item $exe bundle\ldsc.exe
          foreach ($f in 'LICENSE','AUTHORS','NOTICE','CREDITS') {
            if (Test-Path $f) { Copy-Item $f bundle\ }
          }
          Compress-Archive -Path bundle\* -DestinationPath "dist/ldsc_${{ matrix.triplet }}.zip" -Force

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p dist bundle
          bin="build/ldsc"; [[ -f "build/Release/ldsc" ]] && bin="build/Release/ldsc"
          cp "$bin" bundle/ldsc
          chmod +x bundle/ldsc
          for f in LICENSE AUTHORS NOTICE CREDITS; do [[ -f "$f" ]] && cp "$f" bundle/ || true; done
          tar czf "dist/ldsc_${{ matrix.triplet }}.tar.gz" -C bundle .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldsc-${{ matrix.triplet }}
          path: dist/*

  macos-universal:
    name: Create macOS universal binary
    needs: build
    runs-on: macos-14
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ldsc-macos-x86_64
          path: mac_x86
      - uses: actions/download-artifact@v4
        with:
          name: ldsc-macos-arm64
          path: mac_arm
      - name: Combine with lipo
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p out
          tar xzf mac_x86/*.tar.gz
          mv ldsc ldsc_x86_64
          tar xzf mac_arm/*.tar.gz
          mv ldsc ldsc_arm64
          lipo -create -output ldsc ldsc_x86_64 ldsc_arm64
          tar czf out/ldsc_macos-universal.tar.gz ldsc
      - uses: actions/upload-artifact@v4
        with:
          name: ldsc-macos-universal
          path: out/*

  release:
    name: Publish GitHub Release
    needs: [build-linux, build, macos-universal]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Gather files
        run: |
          mkdir out
          find artifacts -type f -name '*.zip' -o -name '*.tar.gz' -print0 | xargs -0 -I{} cp {} out/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
          generate_release_notes: true

